services:
  - type: web
    name: rabbitmq
    env: docker
    plan: free
    disk:
      name: rabbitmq-disk
      mountPath: /var/lib/rabbitmq
      sizeGB: 1
    envVars:
      - key: RABBITMQ_ERLANG_COOKIE
        generateValue: true
      - key: RABBITMQ_DEFAULT_USER
        value: rabbitmq
      - key: RABBITMQ_DEFAULT_PASS
        generateValue: true
    startCommand: >
      sh -c "
        rabbitmq-server & 
        sleep 10 && 
        socat TCP-LISTEN:80,fork TCP:localhost:5672 &
        socat TCP-LISTEN:15672,fork TCP:localhost:15672 &&
        wait
      "
